import type { Metadata } from "next";
import Link from "next/link";
import { ShieldCheck } from "lucide-react";
import { ProfitShareForm } from "@/components/admin/ProfitShareForm";
import { AdminActionForm } from "@/components/admin/AdminActionForm";
import { adminReverseProfitShare } from "./actions";
import { formatUsdt } from "@/lib/money";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = { title: "Admin · Profit share" };

function formatDate(date: Date) { return date.toLocaleString("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", hour12: true }); }

export default async function AdminProfitSharePage() {
  const runs = await prisma.profitShareRun.findMany({ orderBy: { createdAt: "desc" }, include: { admin: { select: { fullName: true, email: true } }, reversedBy: { select: { fullName: true, email: true } }, allocations: { where: { companyShare: { gt: 0 } }, orderBy: { companyShare: "desc" }, include: { user: { select: { id: true, fullName: true, email: true } } } } } });
  const newestActiveRunId = runs.find((run) => !run.reversedAt)?.id;
  const lifetimeTaken = runs.filter((run) => !run.reversedAt).reduce((sum, run) => sum + Number(run.totalCompanyShare), 0);
  return <div className="mx-auto max-w-7xl space-y-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow">Company earnings</p><h1 className="mt-2 font-serif text-3xl text-ink">Profit <em className="gold-text italic">share</em></h1><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-dim">A settlement deducts the company share directly from investor holdings and from the central trading balance. There is no company trading account.</p></div><span className="inline-flex w-fit items-center gap-1.5 rounded-full border border-positive/25 bg-positive/8 px-3 py-1.5 text-xs text-positive"><ShieldCheck className="size-3.5"/>Manual settlement only</span></header>
    <section className="grid gap-3 sm:grid-cols-2"><article className="glass-card rounded-xl p-5"><p className="text-[10px] uppercase tracking-[0.14em] text-ink-faint">Active settlements</p><p className="mt-2 font-mono text-xl text-ink">{runs.filter((run) => !run.reversedAt).length}</p></article><article className="glass-card rounded-xl p-5"><p className="text-[10px] uppercase tracking-[0.14em] text-ink-faint">Total company share taken</p><p className="mt-2 font-mono text-xl text-positive">{formatUsdt(lifetimeTaken)} USD</p></article></section>
    <section className="glass-card rounded-2xl p-5 sm:p-7"><p className="eyebrow">New settlement</p><h2 className="mt-2 font-serif text-2xl text-ink">Preview company profit share</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-ink-dim">Only profit above each investor’s high-water mark is eligible. Deposits, withdrawals and internal transfers are excluded.</p><div className="mt-6"><ProfitShareForm/></div></section>
    <section className="glass-card rounded-2xl p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="eyebrow">Audit trail</p><h2 className="mt-2 font-serif text-2xl text-ink">Settlement history</h2></div><span className="font-mono text-xs text-ink-faint">{runs.length} runs</span></div>
      <div className="mt-5 space-y-3">{runs.map((run) => <details key={run.id} className="overflow-hidden rounded-xl border border-gold-600/15 bg-black/10"><summary className="grid cursor-pointer gap-3 px-4 py-4 sm:grid-cols-4"><div><p className="text-sm text-ink">{run.frequency === "WEEKLY" ? "Weekly" : "Monthly"} · {run.periodKey}</p><p className="mt-1 text-[10px] text-ink-faint">{formatDate(run.createdAt)}</p></div><div><p className="text-[10px] text-ink-faint">ELIGIBLE PROFIT</p><p className="mt-1 font-mono text-xs text-ink">{formatUsdt(run.totalEligibleProfit)} USD</p></div><div><p className="text-[10px] text-ink-faint">COMPANY SHARE</p><p className="mt-1 font-mono text-xs text-positive">{formatUsdt(run.totalCompanyShare)} USD</p></div><div><p className="text-[10px] text-ink-faint">STATUS</p><p className="mt-1 text-xs text-ink">{run.reversedAt ? "Reversed" : "Settled"}</p></div></summary>
        <div className="flex items-center justify-between gap-4 border-t border-gold-600/15 px-4 py-3"><p className="text-xs text-ink-faint">Confirmed by {run.admin.fullName ?? run.admin.email}{run.reversedAt ? ` · reversed ${formatDate(run.reversedAt)}` : ""}</p>{!run.reversedAt && run.id === newestActiveRunId && <AdminActionForm action={adminReverseProfitShare} submitLabel="Undo settlement" pendingLabel="Undoing…" variant="danger" confirmMessage="Undo this settlement and return the exact value to investors?"><input type="hidden" name="runId" value={run.id}/></AdminActionForm>}</div>
        <div className="overflow-x-auto border-t border-gold-600/15"><table className="w-full min-w-[42rem] text-left text-xs"><thead className="bg-vault-950/35 text-ink-faint"><tr><th className="px-4 py-3">Investor</th><th className="px-4 py-3">Eligible profit</th><th className="px-4 py-3">Company share</th><th className="px-4 py-3">Units removed</th></tr></thead><tbody className="divide-y divide-gold-600/10">{run.allocations.map((allocation) => <tr key={allocation.id}><td className="px-4 py-3"><Link href={`/admin/investors/${allocation.user.id}`} className="text-ink hover:text-gold-300">{allocation.user.fullName ?? allocation.user.email}</Link></td><td className="px-4 py-3 font-mono">{formatUsdt(allocation.eligibleProfit)} USD</td><td className="px-4 py-3 font-mono text-gold-300">{formatUsdt(allocation.companyShare)} USD</td><td className="px-4 py-3 font-mono text-ink-dim">{formatUsdt(allocation.unitsTransferred,6)}</td></tr>)}</tbody></table></div>
      </details>)}{runs.length === 0 && <p className="rounded-xl border border-dashed border-gold-600/20 px-4 py-10 text-center text-sm text-ink-faint">No profit-share settlements yet.</p>}</div>
    </section>
  </div>;
}